"""initial_migration

Revision ID: fd82ff2afbaf
Revises: 
Create Date: 2026-10-02 16:23:31.880860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd82ff2afbaf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('vehicle_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_device_id'), 'vehicles', ['device_id'], unique=True)
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SAFE', 'WARNING', 'CRITICAL', name='safetystatus'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('alcohol_status', sa.String(length=50), nullable=True),
    sa.Column('rash_driving_status', sa.String(length=50), nullable=True),
    sa.Column('buzzer_action', sa.String(length=50), nullable=True),
    sa.Column('engine_state', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('alcohol_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('accel_x', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('accel_y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('accel_z', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('gyro_x', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('gyro_y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('gyro_z', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('current_risk_score', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.Enum('SAFE', 'WARNING', 'CRITICAL', name='safetystatus'), nullable=False),
    sa.Column('engine_state', sa.String(length=50), nullable=False),
    sa.Column('buzzer_state', sa.String(length=50), nullable=False),
    sa.Column('gps_connected', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_status')
    op.drop_table('sensor_readings')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_vehicles_device_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
